name: Latest
on:
  push:
    branches:
    - master
jobs:
  latest:
    name: Latest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Install goreleaser
        run: |
          curl -sLO https://github.com/goreleaser/goreleaser/releases/download/v0.116.0/goreleaser_amd64.deb
          sudo dpkg -i goreleaser_amd64.deb
          rm goreleaser_amd64.deb

      - name: GCR Setup
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.MY_GCLOUD_AUTH }}

      - name: GCR Auth
        uses: actions/gcloud/cli@master
        with:
          args: "auth configure-docker"

      - name: Runs goreleaser
        run: goreleaser release --snapshot --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: push images
        uses: actions/gcloud/cli@master
        with:
          args: "docker -- push gcr.io/k8s-staging-capi-kubeadm/manager"
